---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

library(plyr)
library(dplyr)

## Loading and preprocessing the data

activity.data = read.csv(unz("activity.zip", "activity.csv"))

activity.data = mutate(activity.data, date = as.Date(activity.data$date, "%Y-%m-%d"))

## What is mean total number of steps taken per day?

total.steps.per.day = ddply(activity.data, .(date), summarize, total.steps = sum(steps))

total.steps = with(total.steps.per.day, total.steps[!is.na(total.steps)])
hist(total.steps, breaks = 10)

mean.total.steps = mean(total.steps)
median.total.steps = median(total.steps)
print(mean.total.steps)
print(median.total.steps)

## What is the average daily activity pattern?

mean.steps.per.interval = ddply(activity.data, .(interval), summarize, mean.steps = mean(steps, na.rm = T))
with(mean.steps.per.interval, plot(interval, mean.steps, type="l"))

max.interval = with(mean.steps.per.interval, interval[which.max(mean.steps)])
print(max.interval)

## Imputing missing values

total.na = sum(is.na(activity.data$steps))
print(total.na)

# There is only missing data when there are no measurements whatsoever for an entire day. Therefore, we must transplant information from the other days in the dataset. The most unbiased procedure available is to take the mean steps from every recorded interval as the reported steps for missing intervals.

activity.data.imputed = activity.data
activity.data.imputed$steps[is.na(activity.data.imputed$steps)] = mean.steps.per.interval$mean.steps

total.steps.per.day.imputed = ddply(activity.data.imputed, .(date), summarize, total.steps = sum(steps))
total.steps.imputed = total.steps.per.day.imputed$total.steps
hist(total.steps.imputed, breaks = 10)
mean.total.steps.imputed = mean(total.steps.imputed)
median.total.steps.imputed = median(total.steps.imputed)
print(mean.total.steps.imputed)
print(median.total.steps.imputed)

# The mean number of total steps hasn't changed, but the median number of total steps has. This makes sense, as we've added eight more days to the dataset where the total number of steps is equal to the mean number of steps

## Are there differences in activity patterns between weekdays and weekends?

day.of.week = as.factor(ifelse(weekdays(activity.data.imputed$date) %in% c("Saturday", "Sunday"), "weekend", "weekday"))